version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: leclub_development
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    command: redis-server
    ports:
      - "6380:6379"

  web:
    build: .
    command: bundle exec rails server -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    stdin_open: true
    tty: true

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development

  tailwind:
    build: .
    command: bundle exec rails tailwindcss:watch[always]
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      - web
    environment:
      RAILS_ENV: development
    tty: true

volumes:
  postgres_data:
  bundle_cache: