[phases.setup]
nixPkgs = ["...", "postgresql"]

[variables]
RAILS_ENV = "production"
SECRET_KEY_BASE = "dummy-key-for-assets"
DATABASE_URL = "postgresql://dummy:dummy@dummy:5432/dummy"

[phases.build]
cmds = [
  "bundle install",
  "bundle exec rails assets:precompile"
]

[start]
cmd = "bundle exec rails server -b 0.0.0.0 -p $PORT"