default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: root
  password: password
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pacomien_development

test:
  <<: *default
  database: pacomien_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>