default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: root
  password: password
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "pacomien_development") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "root") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>

test:
  <<: *default
  database: pacomien_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>